name: test

on: [workflow_dispatch, pull_request]

env:
  FOUNDRY_PROFILE: ci
  PORT: ${{ vars.PORT }}
  CHAIN_ID: ${{ vars.CHAIN_ID }}
  HARDFORK: ${{ vars.HARDFORK }}
  ACCOUNT_NUMBER: ${{ vars.ACCOUNT_NUMBER }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  ANVIL_CONFIG_OUT: ${{ vars.ANVIL_CONFIG_OUT }}
  LAST_DEPLOYMENT_PATH: ${{ vars.LAST_DEPLOYMENT_PATH }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --ffi
        id: test
